<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PulseInspector.Core\PulseInspector.Core.csproj" />
    <ProjectReference Include="..\PulseInspector.Application\PulseInspector.Application.csproj" />
    <ProjectReference Include="..\PulseInspector\PulseInspector.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TestData\**\*.csv" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
