<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PulseInspector.Wpf</RootNamespace>
    <AssemblyName>PulseInspector.Wpf</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PulseInspector.Application\PulseInspector.Application.csproj" />
  </ItemGroup>
</Project>
