<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PulseInspector</RootNamespace>
    <AssemblyName>PulseInspector</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**\*.cs" />
    <Compile Remove="Services\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PulseInspector.Core\PulseInspector.Core.csproj" />
  </ItemGroup>
</Project>
